name: Build & Deploy to Heroku 
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    # Job name is Greeting
    name: Build & Deploy
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm test
      - name: Deploy to heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
          HEROKU_APP_NAME: 'line-bot-2pai'
        run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master